In [7]:
# 正规方程线性回归
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from  sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error


In [12]:
# 加载数据
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
raw_df.to_csv('boston_house_datasets.csv')
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
print("数据：\n",data)
print("目标值：\n",target)

数据：
 [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
目标值：
 [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20

In [18]:
# 数据划分
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.2,random_state=42)
print("训练集的形状:\n",x_train.shape)
print("测试集的个数:\n",x_test.shape)

训练集的形状:
 (404, 13)
测试集的个数:
 (102, 13)


In [19]:
# 特征工程- 标准化
transfer  = StandardScaler()
x_train_transfered = transfer.fit_transform(x_train)
x_test_transfered = transfer.fit_transform(x_test)
print("标准化后的结果：\n",x_train_transfered)

标准化后的结果：
 [[ 1.28770177 -0.50032012  1.03323679 ...  0.84534281 -0.07433689
   1.75350503]
 [-0.33638447 -0.50032012 -0.41315956 ...  1.20474139  0.4301838
  -0.5614742 ]
 [-0.40325332  1.01327135 -0.71521823 ... -0.63717631  0.06529747
  -0.65159505]
 ...
 [-0.40547014  2.95931752 -1.30336132 ... -0.59225149  0.37901005
  -0.91069248]
 [ 0.85189733 -0.50032012  1.03323679 ...  0.84534281 -2.69458597
   1.52257036]
 [-0.38135592 -0.50032012 -0.35216694 ...  1.15981657 -3.12158061
  -0.25731635]]


In [29]:
# 机器学习
estimator = LinearRegression()
estimator.fit(x_train_transfered,y_train)

y_pre = estimator.predict(x_test_transfered)
print("预测值为：\n",y_pre)
score = estimator.score(x_test_transfered,y_test)
print("准确率是:\n",score)

## 均方误差
ret = mean_squared_error(y_test,y_pre)
print("均方误差是:\n",ret)

预测值为：
 [31.35290844 38.40284489 16.55844736 26.58918077 19.91977056 25.1731892
 19.37308702 15.75969523 24.33833186 22.27543124 27.41402232 20.8459715
 -6.20896092 23.57543782 20.54735122 27.65901059 22.29464294  6.47668542
 43.51769325 18.65320174 28.94446425 32.10558406 12.40906454 25.57699188
 18.88974664 16.83102191 24.5039016  15.70326165 24.46241833 20.72338387
 24.56515108 26.74159446 27.23281139 18.4655718  18.03968805 19.12254074
 33.3933528  21.22303715 25.76534897 26.2579554  15.40075909 34.23203047
 45.69799351 18.76263812 29.38156443 17.97525818 15.14193938 27.58190643
 21.55178037 32.48247972 23.50448384 37.00274292 17.25100412 27.75973646
 42.81276911 23.75468451 19.94827814 34.41733247 26.88766714 14.09034126
 23.9718086  32.23755994 33.59257448 16.82852653 21.64056532 18.57888398
 21.74112562 27.57817327 32.39925043 12.58182636 22.26578017 28.8742025
 11.88557332 16.0086648  25.64830477  6.56264247 23.01763905 44.38818755
 19.9327619  10.48266618 22.32675614 14.4537174

In [39]:
# 线性回归:梯度下降法

from sklearn.linear_model import SGDRegressor

# 机器学习
estimator2 = SGDRegressor(max_iter=1000,learning_rate="constant", eta0=5e-4,random_state=42)
estimator2.fit(x_train_transfered,y_train)

y_pre = estimator2.predict(x_test_transfered)
print("预测值为：\n",y_pre)
score = estimator2.score(x_test_transfered,y_test)
print("准确率是:\n",score)

## 均方误差
ret = mean_squared_error(y_test,y_pre)
print("均方误差是:\n",ret)

预测值为：
 [31.28435541 38.14353731 17.79978723 26.49159078 20.01377122 25.29587782
 19.41830714 16.06091435 24.11119152 22.53125453 27.15446126 20.92644298
 -5.95207855 23.78699185 20.47257643 27.66064037 21.29993166  6.42348054
 43.1530934  18.76990723 28.58434126 31.62590568 12.61250048 25.71965978
 18.91767811 16.58915937 24.61104009 15.91484443 24.44755937 20.98310189
 24.38976973 26.74616507 27.44842842 18.45834122 17.86543749 19.45573785
 33.48058682 21.07093925 25.80021655 26.1970669  15.62148498 33.58974257
 44.97916878 18.97337336 29.5060282  17.93700456 15.28566971 27.54187104
 21.42239817 32.83398829 23.53793038 36.58683442 17.4821529  28.15177765
 42.64404916 23.71917129 20.050504   33.7750697  26.88773225 14.11527781
 23.91705695 31.82084221 33.35540686 16.92704488 22.44900674 18.49699227
 21.80297837 27.46927946 31.97663618 12.63896477 22.05992872 28.74854635
 12.03121121 16.33445777 25.75907279  6.84292766 23.29204431 43.64617469
 20.04258069 11.65432677 22.56384799 14.2038

In [1]:
# 模型的保存与加载
import joblib 
# 保存
joblib.dump(estimator,'linear_model.pkl')

# 加载
loaded_model = joblib.load('linear_model.pkl')

NameError: name 'estimator' is not defined