numpy与list运算效率比较

In [ ]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())

# %time 是 IPython 环境（如 Jupyter Notebook、JupyterLab 或 IPython 终端）中的魔术命令，用于测量代码执行时间。
%time sum1 = sum(a)

b = np.array(a)
%time sum2 = np.sum(b)


CPU times: total: 859 ms
Wall time: 878 ms
CPU times: total: 172 ms
Wall time: 185 ms


In [4]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
import numpy as np
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros_like(np.array([[1,2,3],[4,5,6]]))

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
arr = np.arange(12).reshape(3, 4)  # 3行4列数组：[[0,1,2,3],[4,5,6,7],[8,9,10,11]]

# 索引
print(arr[1, 2])  # 第2行第3列：6

# 切片（取第1-2行，第2-3列）
print(arr[0:2, 1:3])  # [[1,2], [5,6]]

# 省略号（...）表示剩余维度全取
print(arr[..., 0])  # 取所有行的第1列：[0,4,8]

6
[[1 2]
 [5 6]]
[0 4 8]


In [13]:
arr = np.arange(12).reshape(3, 4)
arr1 = np.array(arr)
arr2 = np.asarray(arr)
print(arr1 is arr)  # False，arr1是新数组
print(arr2 is arr)  # False，arr2是新数组
arr3 = np.array(arr, copy=False)
print(arr3 is arr)  # True，arr3是视图，没有复制数据
arr4  = np.array(arr, copy=True)
print(arr4 is arr)  # False，arr4是新数组
arr1[0,0] = 100
print(arr)  # arr未变，arr1是新数组（深拷贝）
arr3[0,0] = 200
print(arr)  # arr变了，arr3是视图（浅拷贝）
arr2[0,0] = 300
print(arr)  # arr变了，arr2是视图(浅拷贝)

False
True
True
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[200   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[300   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [18]:
np.linspace(1,10,10)  # 1到10之间均匀取10个数

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.logspace(1,10,10)  # 10的1次方到10的10次方之间均匀取10个数

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [3]:
import numpy as np
# 生成均值为5，标准差为2的4个正态分布随机数
normal_arr = np.random.normal(loc=5, scale=2, size=4)
print(normal_arr)

[8.39707347 5.53170346 3.85958499 4.68332059]


In [6]:
import numpy as np
stock_change = np.random.normal(0, 1, (1000, 4))  # 1000天，4只股票的日收益率
print(stock_change)

stock_change.shape


[[ 1.3771075   0.12364326 -1.41385048 -1.39766045]
 [ 0.07364097  0.92377311  2.97921156  0.62156439]
 [-0.06209907 -0.72166567  0.4913917  -0.73991172]
 ...
 [ 0.61397944 -0.06791154  0.29060611  0.3061208 ]
 [-0.48130354  0.53518503 -1.68470953  0.24891564]
 [-0.09356306  0.69132772 -0.12372762 -1.69223715]]


(1000, 4)

In [2]:
# 随机生成正态分布数据，10天，5只股票
import numpy as np
stock_change = np.random.normal(0,1,(10,5))
print(stock_change.shape)
stock_change

(10, 5)


array([[-1.67221058, -0.03361691,  1.35949729, -0.63306747, -0.71262694],
       [ 0.34596492,  1.85224596, -1.71786351, -0.60160283,  0.26150374],
       [ 0.50507308, -0.35768882, -0.10376143,  1.14532648,  1.03846121],
       [ 1.58965515,  1.02752345,  0.42758187, -0.6988511 , -0.1715185 ],
       [-1.78605217,  0.1423032 ,  0.58659325,  0.05924188, -1.75230399],
       [-0.0457947 , -0.80369515,  0.44466889,  0.32884622,  0.55425002],
       [ 0.86579146,  0.00841599, -0.21766049, -0.69439493,  0.97655171],
       [-0.37503141, -1.73148126, -0.29797313, -1.06449395, -0.44464567],
       [ 0.4898468 ,  0.28707916, -0.99263709, -0.39282573,  0.34812766],
       [ 0.87675997,  1.5353445 ,  0.77345248, -1.86644257,  1.75562146]])

In [3]:
# pandas
import pandas as pd
pd.DataFrame(stock_change)

0         1         2         3         4
0 -1.672211 -0.033617  1.359497 -0.633067 -0.712627
1  0.345965  1.852246 -1.717864 -0.601603  0.261504
2  0.505073 -0.357689 -0.103761  1.145326  1.038461
3  1.589655  1.027523  0.427582 -0.698851 -0.171519
4 -1.786052  0.142303  0.586593  0.059242 -1.752304
5 -0.045795 -0.803695  0.444669  0.328846  0.554250
6  0.865791  0.008416 -0.217660 -0.694395  0.976552
7 -0.375031 -1.731481 -0.297973 -1.064494 -0.444646
8  0.489847  0.287079 -0.992637 -0.392826  0.348128
9  0.876760  1.535345  0.773452 -1.866443  1.755621

In [5]:
# 添加行列标签
stock_code = [f'股票{i+1}' for i in range(stock_change.shape[0])]
print(stock_code)

pd.DataFrame(stock_change,index=stock_code)

['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10']


0         1         2         3         4
股票1  -1.672211 -0.033617  1.359497 -0.633067 -0.712627
股票2   0.345965  1.852246 -1.717864 -0.601603  0.261504
股票3   0.505073 -0.357689 -0.103761  1.145326  1.038461
股票4   1.589655  1.027523  0.427582 -0.698851 -0.171519
股票5  -1.786052  0.142303  0.586593  0.059242 -1.752304
股票6  -0.045795 -0.803695  0.444669  0.328846  0.554250
股票7   0.865791  0.008416 -0.217660 -0.694395  0.976552
股票8  -0.375031 -1.731481 -0.297973 -1.064494 -0.444646
股票9   0.489847  0.287079 -0.992637 -0.392826  0.348128
股票10  0.876760  1.535345  0.773452 -1.866443  1.755621

In [8]:
# 设置列标签，采用pd.date_range()自动生成跳过周末的时间
date = pd.date_range(start='20190403',periods=stock_change.shape[1],freq='B')
date

DatetimeIndex(['2019-04-03', '2019-04-04', '2019-04-05', '2019-04-08',
               '2019-04-09'],
              dtype='datetime64[ns]', freq='B')

In [9]:
pd.DataFrame(stock_change,index=stock_code, columns=date)

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票1    -1.672211   -0.033617    1.359497   -0.633067   -0.712627
股票2     0.345965    1.852246   -1.717864   -0.601603    0.261504
股票3     0.505073   -0.357689   -0.103761    1.145326    1.038461
股票4     1.589655    1.027523    0.427582   -0.698851   -0.171519
股票5    -1.786052    0.142303    0.586593    0.059242   -1.752304
股票6    -0.045795   -0.803695    0.444669    0.328846    0.554250
股票7     0.865791    0.008416   -0.217660   -0.694395    0.976552
股票8    -0.375031   -1.731481   -0.297973   -1.064494   -0.444646
股票9     0.489847    0.287079   -0.992637   -0.392826    0.348128
股票10    0.876760    1.535345    0.773452   -1.866443    1.755621